### ISSUE TITLE
建议给软件取个中文名字

### ISSUE THREAD

**Issue by xiexie720** [fqcdn/fq#2]
epoch_access，这个绝大多数中国人不知道怎么念。取了中文名字后，才方便方便传播和推广。

另外，取好名字后，软件目录里的epoch_access.exe，也要改成这个中文名字。这样方便很多电脑水平不高的人，知道就是双击那个exe文件打开的。要不然还真有不少人会在这里吓住。一看目录里全部是英文，就不知道点哪一个了。

**Comment by fqcdn** [comment]
谢谢反馈，Windows版已添加“打开浏览器”快捷方式。
