### ISSUE TITLE
ios有效期80天

### ISSUE THREAD

**Issue by Alvin9999** [fqcdn/fq#4]
80天后过期吗？

**Comment by Alvin9999** [comment]
能否增加一键检测帐号的可用性，如果帐号太多，用户得一个个去尝试，有点麻烦。如果有一键检测功能，那么会更加方便。

**Comment by fqcdn** [comment]
TestFlight 有90天使用限制，所以过一段时间会上传新版延长90天。

**Comment by Alvin9999** [comment]
> TestFlight 有90天使用限制，所以过一段时间会上传新版延长90天。

喔，好

**Comment by Alvin9999** [comment]
之前安装的用户，90天到期后还能用吗？你上传新版延迟90天后，下载链接是否会变？

**Comment by Alvin9999** [comment]
有没有邮箱地址? 有事情想和你沟通下。

**Comment by fqcdn** [comment]
联系方式在页面最后： https://www.fqcdn.xyz/privacy.html

**Comment by Alvin9999** [comment]
If you have any questions about this Privacy Policy, You can contact us by emailing support [at] fqcdn.xyz

邮箱是什么？ @fqcdn.xyz ？

**Comment by fqcdn** [comment]
support [at] fqcdn.xyz
