### ISSUE TITLE
新链接无法下载fair vpn

### ISSUE THREAD

**Issue by Alvin9999** [fqcdn/fq#5]
很多人反馈无法下载

**Comment by JungwooJava** [comment]
我也是iOS无法下载

**Comment by EXthan** [comment]
ios 14.4版无法下载，急求

**Comment by morricdxl** [comment]
TestFlight 人员已经满啦！

**Comment by fqcdn** [comment]
请试用新链接：
https://testflight.apple.com/join/Ao0G8UZD

**Comment by SpongeBab** [comment]
> 请试用新链接：
> https://testflight.apple.com/join/Ao0G8UZD

也是满的

**Comment by SpongeBab** [comment]
> TestFlight 人员已经满啦！

老哥有没有别的啊

**Comment by fqcdn** [comment]
有，请试用 https://testflight.apple.com/join/sdBZzV82

**Comment by rightstone11** [comment]
Thanks
